# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.29.2"
neorg = "8.6.0"
nvim-web-devicons = "0.100"
nvim-navic = "scm"
"rocks-git.nvim" = "1.5.1"
"plenary.nvim"= "scm"
luasnip = "2.3.0"
"comment.nvim" = "0.8.0"
"rocks-dev.nvim" = "1.2.1"
"rocks-config.nvim" = "1.6.0"
"oil.nvim" = "2.9.0"
"none-ls.nvim" = "scm"
"none-ls-extras.nvim" = "scm"

[plugins."lualine.nvim"]
git = "nvim-lualine/lualine.nvim"
rev = "compat-nvim-0.6"

[plugins."barbecue.nvim"]
git = "utilyre/barbecue.nvim"
rev = "v1.2.0"

[plugins."nvim-tree.lua"]
git = "nvim-tree/nvim-tree.lua"
rev = "v1.3.3"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"

[plugins."telescope.nvim"]
git = "nvim-telescope/telescope.nvim"
rev = "nvim-0.6"

[plugins."mason.nvim"]
git = "williamboman/mason.nvim"
rev = "v1.10.0"

[plugins."mason-lspconfig.nvim"]
git = "williamboman/mason-lspconfig.nvim"
rev = "v1.9.0"

[plugins.nvim-lspconfig]
git = "neovim/nvim-lspconfig"
rev = "v0.1.8"

[plugins."lspsaga.nvim"]
git = "nvimdev/lspsaga.nvim"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"

[plugins."onedark.nvim"]
git = "navarasu/onedark.nvim"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.8.1"

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"
# rev = "v0.0.1"
rev = "5260e5e"

[plugins.cmp_luasnip]
git = "saadparwaiz1/cmp_luasnip"

[plugins.nvim-autopairs]
git = "windwp/nvim-autopairs"

[plugins.dashboard-nvim]
git = "nvimdev/dashboard-nvim"

[plugins.cmp-cmdline]
git = "hrsh7th/cmp-cmdline"

[plugins.cmp-buffer]
git = "hrsh7th/cmp-buffer"

[plugins.cmp-path]
git = "hrsh7th/cmp-path"

[plugins."telescope-ui-select.nvim"]
git = "nvim-telescope/telescope-ui-select.nvim"

[plugins."barbar.nvim"]
git = "romgrk/barbar.nvim"
rev = "v1.7.0-beta.4"

[plugins."trouble.nvim"]
git = "folke/trouble.nvim"
rev = "v3.1.0"

[plugins."lspkind.nvim"]
git = "onsails/lspkind.nvim"

[plugins.cmp]
git = "petertriho/cmp-git"

[plugins."which-key.nvim"]
git = "folke/which-key.nvim"
rev = "v1.6.1"

[plugins.alpha-nvim]
git = "goolord/alpha-nvim"

[plugins.nvim-dap]
git = "mfussenegger/nvim-dap"
rev = "0.8.0^{}"

[plugins."neofusion.nvim"]
git = "diegoulloao/neofusion.nvim"

[plugins."indentmini.nvim"]
git = "nvimdev/indentmini.nvim"

[plugins."none-ls-luacheck.nvim"]
git = "gbprod/none-ls-luacheck.nvim"
rev = "v0.0.1"


# Neovim config
[config.options]
number = true
splitbelow = true
splitright = true
wrap = false
expandtab = true
tabstop = 4
shiftwidth = 4
clipboard = "unnamedplus"
scrolloff = 999
virtualedit = "block"
inccommand = "split"
ignorecase = true
termguicolors = true
updatetime = 100
conceallevel = 2
foldlevel = 99
fileformat = "unix"
background = "dark"
backspace = "2"
swapfile = false
