# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.36.1"
nvim-web-devicons = "0.100"
"rocks-git.nvim" = "2.0.1"
"plenary.nvim"= "0.1.4"
luasnip = "2.3.0"
"rocks-config.nvim" = "2.2.0"
"oil.nvim" = "2.11.0"
nvim-ts-autotag = "scm"
nvim-surround = "2.1.5"
"overseer.nvim" = "1.4.0"
"feline.nvim" = "1.6.3"
"conform.nvim" = "7.0.0"
"telescope-undo.nvim" = "scm"
"trouble.nvim" = "3.6.0"
"mason.nvim"= "1.10.0"
# "mason-lspconfig.nvim"= "1.29.0"
# nvim-lspconfig= "0.1.8"
"lspkind.nvim"= "scm"
nvim-autopairs= "scm"
"indent-blankline.nvim"= "3.7.1"
"which-key.nvim"= "3.13.2"
alpha-nvim= "scm"
"rocks-lazy.nvim" = "1.0.0"
"rocks-edit.nvim" = "scm"
friendly-snippets= "scm"
neorg-interim-ls = "1.2.0"
nvim-spectre = "scm"
nvim-notify = "3.13.5"
"sus.nvim" = "1.0.0"
rustaceanvim = "5.1.0"
"todo-comments.nvim" = "1.3.0"
neorg-se = "1.1.10"
"fine-cmdline.nvim" = "scm"
"searchbox.nvim" = "scm"
"flash.nvim" = "2.1.0"

# [plugins.nvim-cmp]
# git = "hrsh7th/nvim-cmp"
# rev = "main"
#
# [plugins.cmp-cmdline]
# version = "scm"
#
# [plugins.cmp-nvim-lsp]
# version = "scm"
#
# [plugins.cmp-path]
# version = "scm"
#
# [plugins.cmp_luasnip]
# version = "scm"

[plugins."image.nvim"]
version = "1.3.0"

[plugins."telescope.nvim"]
version = "scm"

[plugins.'nvim-tree.lua']
version = "1.5.0"

[plugins.'onedarkpro.nvim']
version = "0.8.0"

[plugins.neorg]
version = "9.1.1"

[plugins.neorg-telescope]
version = "1.2.2"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins."nvim-colorizer.lua"]
git = "nvchad/nvim-colorizer.lua"
rev = "194ec600488f7c7229668d0e80bd197f3a2b84ff"

[plugins."telescope-symbols.nvim"]
git = "nvim-telescope/telescope-symbols.nvim"
rev = "a6d0127a53d39b9fc2af75bd169d288166118aec"

[plugins."live-server.nvim"]
git = "barrett-ruth/live-server.nvim"
rev = "5fc8abb727827a09d0ce1b7757d0a4c7b5802b09"

[plugins.neocodeium]
git = "monkoose/neocodeium"
rev = "4a46f6438bcdb21c562f83036bce75c719834072"

[plugins.nvim-emmet]
git = "olrtg/nvim-emmet"
rev = "cde4fb2968704aae5c18b7f8a9bc2508767bb78d"

[plugins."markview.nvim"]
git = "OXY2DEV/markview.nvim"
rev = "main"

[plugins."care.nvim"]
git = "max397574/care.nvim"
rev = "391c9c94e544d7914a2f8991128b24a9ee81b993"
config = false

[plugins.care-lsp]
git = "max397574/care-lsp"
rev = "f7857993ae28bdaa79f7b03f6398e177918a2e38"
config = false

[plugins."neominimap.nvim"]
git = "isrothy/neominimap.nvim"
rev = "v2.4.2"

[plugins."selabel.nvim"]
git = "axlefublr/selabel.nvim"
rev = "v0.0.1"

[plugins."barbar.nvim"]
git = "romgrk/barbar.nvim"
rev = "v1.8.0^{}"

[plugins.nvim-scissors]
git = "chrisgrieser/nvim-scissors"
rev = "58672a4329040a6e8c83f06b1355dd141c127699"

[plugins.nvim-treesitter]
git = 'nvim-treesitter/nvim-treesitter'
rev = 'master'

[config]
plugins_dir = 'tarun/plugins/'
auto_setup = true

# Neovim options
[config.options]
relativenumber = true
number = true
splitbelow = true
splitright = true
wrap = false
expandtab = true
tabstop = 4
shiftwidth = 4
clipboard = "unnamedplus"
scrolloff = 999
virtualedit = "block"
inccommand = "split"
ignorecase = true
termguicolors = true
updatetime = 100
conceallevel = 2
foldlevel = 99
fileformat = "unix"
background = "dark"
backspace = "2"
swapfile = false
laststatus = 3
timeoutlen = 150
signcolumn = 'auto:2'
cmdheight = 0
list = true
listchars = 'tab:» ,nbsp:+,trail:·,eol:↩,'
