[treesitter]
auto_highlight = "all"
auto_install = "prompt"

[rocks]

[plugins]
# Treesitter
"rocks-treesitter.nvim" = "1.1.3"
nvim-treesitter-legacy-api = "0.9.2"
tree-sitter-toml = "scm"
tree-sitter-lua = "scm"
tree-sitter-norg-meta = "0.1.0"
tree-sitter-html = "scm"
tree-sitter-zig = "scm"
tree-sitter-html_tags = "scm"
tree-sitter-regex = "scm"
tree-sitter-javascript = "scm"
tree-sitter-typescript = "scm"
tree-sitter-ecma = "scm"
tree-sitter-rust = "scm"
tree-sitter-tmux = "scm"
tree-sitter-diff = "scm"
tree-sitter-fish = "scm"

"rocks.nvim" = "2.40.2"
nvim-web-devicons = "0.100"
"rocks-git.nvim" = "2.3.1"
"plenary.nvim" = "scm"
luasnip = { version = "2.3.0", event = 'InsertEnter' }
"rocks-config.nvim" = "3.0.0"
nvim-ts-autotag = "scm"
nvim-surround = { version = "2.1.5", event = "InsertEnter" }
"overseer.nvim" = { version = "1.4.0", event = "DeferredUIEnter" }
"feline.nvim" = { version = "1.6.3", event = 'BufEnter' }
"conform.nvim" = { version = "8.1.0", event = 'BufWritePre' }
"trouble.nvim" = { version = "3.6.0", event = "DeferredUIEnter" }
"lspkind.nvim" = { version = "scm", event = "InsertEnter" }
nvim-autopairs = { version = "scm", event = 'InsertEnter' }
"which-key.nvim" = { version = "3.13.3", event = 'DeferredUIEnter' }
alpha-nvim = "scm"
"rocks-lazy.nvim" = "1.1.0"
"rocks-edit.nvim" = "scm"
friendly-snippets = { version = "scm", event = 'InsertEnter' }
neorg-interim-ls = { version = "1.2.1" }
nvim-notify = { version = "3.13.5" }
"sus.nvim" = { version = "1.0.0", event = 'DeferredUIEnter' }
rustaceanvim = { version = "5.8.1", ft = 'rust' }
"todo-comments.nvim" = { version = "1.4.0", event = 'DeferredUIEnter' }
neorg-se = { version = "1.1.10" }
"flash.nvim" = { version = "2.1.0" }
nvim-ufo = { version = "1.4.0", event = 'DeferredUIEnter' }
"lazydev.nvim" = { version = "1.8.0" }
"indentmini.nvim" = { version = "scm", event = 'DeferredUIEnter' }
"image.nvim" = { version = "1.3.0", ft = ['markdown', 'norg'] }
nvim-dap = "scm"
"helpview.nvim" = { version = "1.1.0", event = 'DeferredUIEnter' }
"markview.nvim" = { version = "23.1.0", ft = 'markdown' }
"mason.nvim" = "1.10.0"
cmp-buffer = "scm"

[plugins."oil.nvim"]
version = "2.12.2"
keys = [{ lhs = '-', rhs = ':Oil<CR>', desc = 'Oil' }]

[plugins.cmp-path]
version = "scm"

[plugins.cmp_luasnip]
version = "scm"

[plugins."telescope.nvim"]
version = "scm"
event = "DeferredUIEnter"

[plugins.'nvim-tree.lua']
version = "1.6.0"
event = 'DeferredUIEnter'

[plugins.neorg]
version = "9.1.1"

[plugins.neorg-telescope]
version = "1.2.2"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"
event = 'DeferredUIEnter'

[plugins."nvim-colorizer.lua"]
git = "nvchad/nvim-colorizer.lua"
rev = "master"
config = "tarun.plugins.colorizer"

[plugins."telescope-symbols.nvim"]
git = "nvim-telescope/telescope-symbols.nvim"
rev = "master"
event = 'DeferredUIEnter'

[plugins.neocodeium]
git = "monkoose/neocodeium"
rev = "main"

[plugins."barbar.nvim"]
git = "romgrk/barbar.nvim"
rev = "v1.9.1^{}"
event = 'DeferredUIEnter'

[plugins.nvim-scissors]
git = "chrisgrieser/nvim-scissors"
rev = "main"
event = 'InsertEnter'

[plugins.neorg_extras]
git = "juniorsundar/neorg_extras"
rev = "v0.3.1"

[plugins."dress.nvim"]
git = "axlefublr/dress.nvim"
rev = "4c293b1d2688dbe06d0533dcbd98c3ad7f2534b7"
event = 'DeferredUIEnter'

[plugins."lsp_lines.nvim"]
git = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"
event = 'LspAttach'
rev = "v3.0.0^{}"

[plugins."care.nvim"]
git = "max397574/care.nvim"
rev = "main"

[plugins.care-cmp]
git = "max397574/care-cmp"
rev = 'main'

[plugins.nvim]
git = "catppuccin/nvim"
rev = "v1.9.0"

[plugins.nvim-rip-substitute]
git = "chrisgrieser/nvim-rip-substitute"
rev = "main"

[plugins."tiny-code-action.nvim"]
git = "rachartier/tiny-code-action.nvim"
rev = "25874e2f2197fe5ae939b824f0f983c9a062ad7e"

[plugins."live-preview.nvim"]
git = "brianhuster/live-preview.nvim"
rev = "e92c6099bc0177378e8a9dfa169de24b109a5ad9"
ft = ['markdown', 'html', 'css', 'javscript']

[bundles.completion] 
items = [
    "care.nvim",
    "cmp-path",
    "care-cmp",
    "cmp_luasnip",
    "cmp-buffer",
]
config = "tarun.plugins.care"

[config]
plugins_dir = 'tarun/plugins/'
auto_setup = true

# Neovim options
[config.options]
relativenumber = true
number = true
splitbelow = true
splitright = true
wrap = false
expandtab = true
tabstop = 4
shiftwidth = 4
clipboard = "unnamedplus"
scrolloff = 999
virtualedit = "block"
inccommand = "split"
ignorecase = true
termguicolors = true
updatetime = 100
conceallevel = 2
foldlevel = 99
fileformat = "unix"
background = "dark"
backspace = "2"
swapfile = false
laststatus = 3
timeoutlen = 150
signcolumn = 'yes:2'
cmdheight = 0
