# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.32.0"
nvim-web-devicons = "0.100"
"rocks-git.nvim" = "1.5.1"
"plenary.nvim"= "0.1.4"
luasnip = "2.3.0"
"rocks-config.nvim" = "2.1.1"
"oil.nvim" = "2.10.0"
nvim-ts-autotag = "scm"
nvim-surround = "2.1.5"
"overseer.nvim" = "1.4.0"
"bufferline.nvim" = "4.6.1"
"feline.nvim" = "1.6.2"
"conform.nvim" = "6.0.0"
"better-escape.nvim" = "1.0.0"
"telescope-undo.nvim" = "scm"
"trouble.nvim" = "3.4.3"
"mason.nvim"= "1.10.0"
"mason-lspconfig.nvim"= "1.29.0"
nvim-treesitter= "0.9.2"
nvim-lspconfig= "0.1.8"
"lspkind.nvim"= "scm"
nvim-autopairs= "scm"
"indent-blankline.nvim"= "3.7.0"
"which-key.nvim"= "2.1.0"
alpha-nvim= "scm"
"rocks-lazy.nvim" = "scm"

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"

[plugins."telescope.nvim"]
version = "scm"
cmd = ["Telescope", "Telescope find_files", "Telescope live_grep", "Telescope oldfiles"]

[plugins.cmp-cmdline]
version = "scm"
# event = "InsertEnter"

[plugins.cmp-nvim-lsp]
version = "scm"
# event = "InsertEnter"

[plugins.cmp-path]
version = "scm"
# event = "InsertEnter"

[plugins.cmp_luasnip]
version = "scm"
# event = "InsertEnter"

[plugins.'nvim-tree.lua']
version = "1.4.0"
keys = {lhs = '<leader>ee', rhs = '<cmd>NvimTreeToggle<cr>', desc = 'Toggle NvimTree'}

[plugins.'onedarkpro.nvim']
version = "0.8.0"
colorscheme = [
    "onedark",
    "onedark_vivid",
    "onedark_dark",
    "onelight",
]

[plugins.neorg]
version = "8.8.1"
ft = 'norg'

[plugins.neorg-telescope]
version = "1.1.0"
ft = 'norg'

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins."nvim-colorizer.lua"]
git = "norcalli/nvim-colorizer.lua"

[plugins.friendly-snippets]
git = "rafamadriz/friendly-snippets"

[plugins."telescope-symbols.nvim"]
git = "nvim-telescope/telescope-symbols.nvim"

[plugins."live-server.nvim"]
git = "barrett-ruth/live-server.nvim"

[plugins.supermaven-nvim]
git = "supermaven-inc/supermaven-nvim"

[plugins.nvim-emmet]
git = "olrtg/nvim-emmet"

# Neovim config
[config.options]
relativenumber = true
number = true
splitbelow = true
splitright = true
wrap = false
expandtab = true
tabstop = 4
shiftwidth = 4
clipboard = "unnamedplus"
scrolloff = 999
virtualedit = "block"
inccommand = "split"
ignorecase = true
termguicolors = true
updatetime = 100
conceallevel = 2
foldlevel = 99
fileformat = "unix"
background = "dark"
backspace = "2"
swapfile = false
laststatus = 3
timeoutlen = 150
