# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.29.2"
neorg = "8.6.0"
nvim-web-devicons = "0.100"
nvim-navic = "scm"
"rocks-git.nvim" = "1.5.1"
"plenary.nvim"= "scm"
luasnip = "2.3.0"
"comment.nvim" = "0.8.0"
"rocks-dev.nvim" = "1.2.2"
"rocks-config.nvim" = "1.6.0"
"oil.nvim" = "2.9.0"
"none-ls.nvim" = "scm"
"none-ls-extras.nvim" = "scm"
"nui.nvim" = "0.3.0"
"toggleterm.nvim" = "2.11.0"
nvim-notify = "3.13.5"
"noice.nvim" = "4.0.1"
"lazygit.nvim" = "scm"
"rocks-treesitter.nvim" = "scm"
nvim-ts-autotag = "scm"
"hardtime.nvim" = "scm"
nvim-surround = "2.1.5"
treesj = "scm"
"todo-comments.nvim" = "1.2.0"
neorg-telescope = "1.1.0"
"codeium.nvim" = "scm"
"telescope-dap.nvim" = "scm"
"telescope-ui-select.nvim"= "scm"
"fidget.nvim" = "1.4.1"
"overseer.nvim" = "1.4.0"
"dressing.nvim" = "2.2.1"
fzf-lua = "0.0.1301"

[plugins."lualine.nvim"]
git = "nvim-lualine/lualine.nvim"
rev = "compat-nvim-0.6"

[plugins."nvim-tree.lua"]
git = "nvim-tree/nvim-tree.lua"
rev = "v1.3.3"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"

[plugins."telescope.nvim"]
git = "nvim-telescope/telescope.nvim"
rev = "nvim-0.6"

[plugins."mason.nvim"]
git = "williamboman/mason.nvim"
rev = "v1.10.0"

[plugins."mason-lspconfig.nvim"]
git = "williamboman/mason-lspconfig.nvim"
rev = "v1.9.0"

[plugins.nvim-lspconfig]
git = "neovim/nvim-lspconfig"
rev = "v0.1.8"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"

[plugins."onedark.nvim"]
git = "navarasu/onedark.nvim"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.8.1"

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"
rev = "5260e5e"

[plugins.cmp_luasnip]
git = "saadparwaiz1/cmp_luasnip"

[plugins.nvim-autopairs]
git = "windwp/nvim-autopairs"

[plugins.cmp-cmdline]
git = "hrsh7th/cmp-cmdline"

[plugins.cmp-buffer]
git = "hrsh7th/cmp-buffer"

[plugins.cmp-path]
git = "hrsh7th/cmp-path"

[plugins."barbar.nvim"]
git = "romgrk/barbar.nvim"
rev = "v1.7.0-beta.4"

[plugins."lspkind.nvim"]
git = "onsails/lspkind.nvim"

[plugins.cmp]
git = "petertriho/cmp-git"

[plugins."which-key.nvim"]
git = "folke/which-key.nvim"
rev = "v1.6.1"

[plugins.alpha-nvim]
git = "goolord/alpha-nvim"

[plugins.nvim-dap]
git = "mfussenegger/nvim-dap"
rev = "0.8.0^{}"

[plugins."none-ls-luacheck.nvim"]
git = "gbprod/none-ls-luacheck.nvim"
rev = "v0.0.1"

[plugins.nvim-cursorline]
git = "yamatsum/nvim-cursorline"

[plugins."autosave.nvim"]
git = "0x00-ketsu/autosave.nvim"
rev = "v1.0^{}"

[plugins."indent-blankline.nvim"]
git = "lukas-reineke/indent-blankline.nvim"
rev = "v3.6.2"

[plugins."nvim-colorizer.lua"]
git = "norcalli/nvim-colorizer.lua"

[plugins."duckytype.nvim"]
git = "kwakzalver/duckytype.nvim"

[plugins.supermaven-nvim]
git = "supermaven-inc/supermaven-nvim"

[plugins."codeium.vim"]
git = "Exafunction/codeium.vim"
rev = "1.8.5"

[plugins.friendly-snippets]
git = "rafamadriz/friendly-snippets"

[plugins."outline.nvim"]
git = "hedyhli/outline.nvim"
rev = "v1.0.0^{}"

[plugins."telescope-symbols.nvim"]
git = "nvim-telescope/telescope-symbols.nvim"

[plugins."mason-null-ls.nvim"]
git = "jay-babu/mason-null-ls.nvim"
rev = "v2.6.0"

[plugins."live-server.nvim"]
git = "barrett-ruth/live-server.nvim"

[plugins."lazydev.nvim"]
git = "folke/lazydev.nvim"
rev = "v1.5.0"

# Neovim config
[config.options]
relativenumber = true
number = true
splitbelow = true
splitright = true
wrap = false
expandtab = true
tabstop = 4
shiftwidth = 4
clipboard = "unnamedplus"
scrolloff = 999
virtualedit = "block"
inccommand = "split"
ignorecase = true
termguicolors = true
updatetime = 100
conceallevel = 2
foldlevel = 99
fileformat = "unix"
background = "dark"
backspace = "2"
swapfile = false

# Treesitter options
# [treesitter]
# auto_highlight = "all"
# auto_install = "prompt"
