# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.31.3"
neorg = "8.7.1"
nvim-web-devicons = "0.100"
"rocks-git.nvim" = "1.5.1"
"plenary.nvim"= "scm"
luasnip = "2.3.0"
"rocks-config.nvim" = "2.0.0"
"oil.nvim" = "2.10.0"
"toggleterm.nvim" = "2.11.0"
nvim-ts-autotag = "scm"
nvim-surround = "2.1.5"
neorg-telescope = "1.1.0"
"overseer.nvim" = "1.4.0"
"bufferline.nvim" = "4.6.1"
"feline.nvim" = "1.6.2"
"conform.nvim" = "6.0.0"
"better-escape.nvim" = "1.0.0"
"telescope-undo.nvim" = "scm"
"trouble.nvim" = "3.4.3"
"nvim-tree.lua"= "1.4.0"
"mason.nvim"= "1.10.0"
"mason-lspconfig.nvim"= "1.29.0"
nvim-treesitter= "0.9.2"
"telescope.nvim"= "scm"
nvim-lspconfig= "0.1.8"
cmp-nvim-lsp= "scm"
"onedarkpro.nvim" = "0.8.0"
cmp-path= "scm"
cmp_luasnip= "scm"
"lspkind.nvim"= "scm"
nvim-autopairs= "scm"
"indent-blankline.nvim"= "3.6.3"
"which-key.nvim"= "2.1.0"
alpha-nvim= "scm"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"
rev = "5260e5e"

[plugins."nvim-colorizer.lua"]
git = "norcalli/nvim-colorizer.lua"

[plugins.friendly-snippets]
git = "rafamadriz/friendly-snippets"

[plugins."telescope-symbols.nvim"]
git = "nvim-telescope/telescope-symbols.nvim"

[plugins."live-server.nvim"]
git = "barrett-ruth/live-server.nvim"

[plugins.cmp-cmdline]
git = "hrsh7th/cmp-cmdline"

[plugins.supermaven-nvim]
git = "supermaven-inc/supermaven-nvim"

[plugins.nvim-emmet]
git = "olrtg/nvim-emmet"

# Neovim config
[config.options]
relativenumber = true
number = true
splitbelow = true
splitright = true
wrap = false
expandtab = true
tabstop = 4
shiftwidth = 4
clipboard = "unnamedplus"
scrolloff = 999
virtualedit = "block"
inccommand = "split"
ignorecase = true
termguicolors = true
updatetime = 100
conceallevel = 2
foldlevel = 99
fileformat = "unix"
background = "dark"
backspace = "2"
swapfile = false
laststatus = 3
timeoutlen = 150
