# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.36.1"
nvim-web-devicons = "0.100"
"rocks-git.nvim" = "2.0.1"
"plenary.nvim" = "scm"
luasnip = { version = "2.3.0", event = 'InsertEnter' }
"rocks-config.nvim" = "2.2.0"
nvim-ts-autotag = "scm"
nvim-surround = "2.1.5"
"overseer.nvim" = "1.4.0"
"feline.nvim" = { version = "1.6.3", event = 'BufEnter' }
"conform.nvim" = { version = "7.0.0", event = 'BufWritePre' }
"trouble.nvim" = "3.6.0"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.29.0"
nvim-lspconfig = "0.1.8"
"lspkind.nvim" = "scm"
nvim-autopairs = { version = "scm", event = 'DeferredUIEnter' }
"which-key.nvim" = { version = "3.13.2", event = 'DeferredUIEnter' }
alpha-nvim = "scm"
"rocks-lazy.nvim" = "1.0.1"
"rocks-edit.nvim" = "scm"
friendly-snippets = { version = "scm", event = 'InsertEnter' }
neorg-interim-ls = { version = "1.2.0" }
nvim-spectre = { version = "scm", event = 'DeferredUIEnter' }
nvim-notify = "3.13.5"
"sus.nvim" = { version = "1.0.0", event = 'DeferredUIEnter' }
rustaceanvim = { version = "5.2.0", ft = 'rs' }
"todo-comments.nvim" = { version = "1.3.0", event = 'DeferredUIEnter' }
neorg-se = { version = "1.1.10" }
"flash.nvim" = { version = "2.1.0", keys = { lhs = 's', rhs = '<cmd>lua require("flash").jump()<CR>', desc = 'Flash' } }
nvim-treesitter = "scm"
nvim-ufo = { version = "1.4.0", event = 'DeferredUIEnter' }
"lazydev.nvim" = { version = "1.8.0", ft = 'lua' }
"indentmini.nvim" = { version = "scm", event = 'DeferredUIEnter' }
# "care.nvim" = { version = "scm", config = false, opt = true }
"care.nvim" = { version = "scm", config = false }

# "oil.nvim" = "2.11.0"

[plugins."oil.nvim"]
version = '2.11.0'
keys = [{ lhs = '-', rhs = ':Oil<CR>', desc = 'Oil' }]

[plugins.nvim-cmp]
version = "scm"
opt = true

[plugins.cmp-cmdline]
version = "scm"
opt = true

[plugins.cmp-nvim-lsp]
version = "scm"
opt = true

[plugins.cmp-path]
version = "scm"
opt = true

[plugins.cmp_luasnip]
version = "scm"
opt = true

[plugins."image.nvim"]
git = '3rd/image.nvim'
# version = "1.3.0"
rev = 'master'
ft = ['markdown', 'norg']

[plugins."telescope.nvim"]
version = "scm"

[plugins.'nvim-tree.lua']
version = "1.6.0"
event = 'DeferredUIEnter'

[plugins.'onedarkpro.nvim']
version = "0.8.0"
colorscheme = ['onedark', 'onedark_vivd', 'onelight', 'onedark_dark']

[plugins.neorg]
version = "9.1.1"
# ft = 'norg'

[plugins.neorg-telescope]
version = "1.2.2"
# ft = 'norg'

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"
event = 'DeferredUIEnter'

[plugins."nvim-colorizer.lua"]
git = "nvchad/nvim-colorizer.lua"
rev = "master"
event = 'DeferredUIEnter'

[plugins."telescope-symbols.nvim"]
git = "nvim-telescope/telescope-symbols.nvim"
rev = "master"
event = 'DeferredUIEnter'

[plugins."live-server.nvim"]
git = "barrett-ruth/live-server.nvim"
rev = "main"
ft = ['html', 'css', 'js']

[plugins.neocodeium]
git = "monkoose/neocodeium"
rev = "main"
config = false

[plugins.nvim-emmet]
git = "olrtg/nvim-emmet"
rev = "main"
# event = 'DeferredUIEnter'
ft = ['html', 'css', 'js']

[plugins."markview.nvim"]
git = "OXY2DEV/markview.nvim"
rev = "main"
ft = 'markdown'

[plugins.care-lsp]
git = "max397574/care-lsp"
rev = "main"
config = false
# opt = true

[plugins."neominimap.nvim"]
git = "isrothy/neominimap.nvim"
rev = "v2.7.1"

[plugins."selabel.nvim"]
git = "axlefublr/selabel.nvim"
rev = "v0.0.1"

[plugins."barbar.nvim"]
git = "romgrk/barbar.nvim"
rev = "v1.9.1^{}"

[plugins.nvim-scissors]
git = "chrisgrieser/nvim-scissors"
rev = "main"
event = 'InsertEnter'

[plugins.neorg_extras]
git = "juniorsundar/neorg_extras"
rev = "v0.1.0"

[plugins."dress.nvim"]
git = "axlefublr/dress.nvim"

[plugins."wife.nvim"]
git = "axlefublr/wife.nvim"

[config]
plugins_dir = 'tarun/plugins/'
auto_setup = true

# Neovim options
[config.options]
relativenumber = true
number = true
splitbelow = true
splitright = true
wrap = false
expandtab = true
tabstop = 4
shiftwidth = 4
clipboard = "unnamedplus"
scrolloff = 999
virtualedit = "block"
inccommand = "split"
ignorecase = true
termguicolors = true
updatetime = 100
conceallevel = 2
foldlevel = 99
fileformat = "unix"
background = "dark"
backspace = "2"
swapfile = false
laststatus = 3
timeoutlen = 150
signcolumn = 'auto:2'
cmdheight = 0
