# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.35.0"
nvim-web-devicons = "0.100"
"rocks-git.nvim" = "1.5.1"
"plenary.nvim"= "0.1.4"
luasnip = "2.3.0"
"rocks-config.nvim" = "2.1.3"
"oil.nvim" = "2.11.0"
nvim-ts-autotag = "scm"
nvim-surround = "2.1.5"
"overseer.nvim" = "1.4.0"
"bufferline.nvim" = "4.6.1"
"feline.nvim" = "1.6.2"
"conform.nvim" = "6.0.0"
"telescope-undo.nvim" = "scm"
"trouble.nvim" = "3.5.1"
"mason.nvim"= "1.10.0"
"mason-lspconfig.nvim"= "1.29.0"
nvim-lspconfig= "0.1.8"
"lspkind.nvim"= "scm"
nvim-autopairs= "scm"
"indent-blankline.nvim"= "3.7.1"
"which-key.nvim"= "2.1.0"
alpha-nvim= "scm"
"rocks-lazy.nvim" = "scm"
"rocks-edit.nvim" = "scm"
nvim-cmp= "scm"
friendly-snippets= "scm"
neorg-interim-ls = "1.0.1"
nvim-spectre = "scm"
"rocks-treesitter.nvim" = "scm"
"headlines.nvim" = "scm"

[plugins."image.nvim"]
version = "1.3.0"
event = "DeferredUIEnter"

[plugins."sus.nvim"]
version = "master"
event = "DeferredUIEnter"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"

[plugins."lsp_lines.nvim"]
git = "https://git.sr.ht/~whynothugo/lsp_lines.nvim"

[plugins."telescope.nvim"]
version = "scm"
# cmd = ["Telescope", "Telescope find_files", "Telescope live_grep", "Telescope oldfiles", "Telescope symbols"]
event = "DeferredUIEnter"

[plugins.cmp-cmdline]
version = "scm"
# event = "InsertEnter"

[plugins.cmp-nvim-lsp]
version = "scm"
# event = "InsertEnter"

[plugins.cmp-path]
version = "scm"
# event = "InsertEnter"

[plugins.cmp_luasnip]
version = "scm"
# event = "InsertEnter"

[plugins.'nvim-tree.lua']
version = "1.4.0"
# keys = {lhs = '<leader>ee', rhs = '<cmd>NvimTreeToggle<cr>', desc = 'Toggle NvimTree'}
event = "DeferredUIEnter"

[plugins.'onedarkpro.nvim']
version = "0.8.0"
# colorscheme = [
#     "onedark",
#     "onedark_vivid",
#     "onedark_dark",
#     "onelight",
# ]
event = "DeferredUIEnter"

[plugins.neorg]
version = "8.9.0"
ft = 'norg'
event = "DeferredUIEnter"

[plugins.neorg-telescope]
version = "1.1.0"
ft = 'norg'
event = "DeferredUIEnter"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins."nvim-colorizer.lua"]
git = "NvChad/nvim-colorizer.lua"

[plugins."telescope-symbols.nvim"]
git = "nvim-telescope/telescope-symbols.nvim"

[plugins."live-server.nvim"]
git = "barrett-ruth/live-server.nvim"

[plugins.supermaven-nvim]
git = "supermaven-inc/supermaven-nvim"

[plugins.nvim-emmet]
git = "olrtg/nvim-emmet"

[plugins."markview.nvim"]
git = "OXY2DEV/markview.nvim"
rev = "dev"

[plugins."neocomplete.nvim"]
git = "max397574/neocomplete.nvim"

[plugins.neocomplete-lsp]
git = "max397574/neocomplete-lsp"

[plugins."telescope-egrepify.nvim"]
git = "fdschmidt93/telescope-egrepify.nvim"

# Neovim options
[config.options]
relativenumber = true
number = true
splitbelow = true
splitright = true
wrap = false
expandtab = true
tabstop = 4
shiftwidth = 4
clipboard = "unnamedplus"
scrolloff = 999
virtualedit = "block"
inccommand = "split"
ignorecase = true
termguicolors = true
updatetime = 100
conceallevel = 2
foldlevel = 99
fileformat = "unix"
background = "dark"
backspace = "2"
swapfile = false
laststatus = 3
timeoutlen = 150
signcolumn = 'auto:2'
