require('tarun.core.lazy')
require('tarun.core.lsp')
require('tarun.core.autocmd')
require('tarun.core.colourscheme')
require('tarun.core.remaps')
require('tarun.core.highlights')
require('tarun.core.options')
