local o = vim.opt

o.number = true
o.relativenumber = true
o.splitbelow = true
o.splitright = true
o.wrap = true
o.expandtab = true
o.tabstop = 4
o.shiftwidth = 4
o.clipboard = 'unnamedplus'
o.scrolloff = 999
o.virtualedit = 'block'
o.inccommand = 'split'
o.ignorecase = true
o.termguicolors = true
o.updatetime = 100
o.conceallevel = 2
o.foldlevel = 99
o.fileformat = 'unix'
o.background = 'dark'
o.swapfile = false
o.laststatus = 3
o.timeoutlen = 150
o.signcolumn = 'auto:2'
o.cmdheight = 0
o.list = true
o.listchars = 'tab:» ,nbsp:+,trail:·,eol:↩,'
