require('tarun.plugins.lualine')
require('tarun.plugins.nvimtree')
require('tarun.plugins.telescope')
require('tarun.plugins.lspconf')
require('tarun.plugins.completions')
require('tarun.plugins.comment')
require('tarun.plugins.gitsigns')
require('tarun.plugins.autopairs')
require('tarun.plugins.dash')
require('tarun.plugins.neorg')
require('tarun.plugins.barbar')
require('tarun.plugins.indent')
require('tarun.plugins.oil')
require('tarun.plugins.none-ls')
require('tarun.plugins.cursorline')
require('tarun.plugins.colorizer')
require('tarun.plugins.duckytype')
require('tarun.plugins.toggleterm')
require('tarun.plugins.overseer')
require('tarun.plugins.dap')
require('tarun.plugins.notify')
require('tarun.plugins.noice')
require('tarun.plugins.autotags')
require('tarun.plugins.surround')
require('tarun.plugins.treesj')
require('tarun.plugins.todo-comments')
-- require('tarun.plugins.codeium')
require('tarun.plugins.treesitter')
require('tarun.plugins.outline')
require('tarun.plugins.live-server')
require('tarun.plugins.dressing')
require('tarun.plugins.lazydev')

-- WARNING: FOR ULTRA HARDCORE VIM USERS ONLY
-- require('tarun.plugins.hardtime')
